[project]
name = "pdf-ocr"
version = "0.1.0"
description = "Simple python script to perform OCR (Optical Character Recognition) on PDF files locally."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
